server:
  port: 8001
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    username: root
    password: root
    
    
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lyusmile.entity